services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kle
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - kle-network
    environment:
      - LC_ALL=tr_TR.UTF-8
      - LANG=tr_TR.UTF-8

  db:
    image: mysql:8.0
    container_name: kle-db
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: kle-db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: root
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    networks:
      - kle-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminkle1
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: laravel_user
      PMA_PASSWORD: root
    networks:
      - kle-network

networks:
  kle-network:

volumes:
  mysql-data:
